services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'
  web:
    build: .
    container_name: web_test
    ports:
      - "5020:5020"
    volumes:
      - .:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
networks:
  my-network-monitor-test:
    driver: bridge
